/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import type { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = [
    'abilities',
    'createdAt',
    'expiresAt',
    'hash',
    'id',
    'lastUsedAt',
    'name',
    'tokenableId',
    'type',
    'updatedAt',
  ] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BattleSchema extends BaseModel {
  static $columns = [
    'battleNumber',
    'closedAt',
    'createdAt',
    'funnelStageId',
    'id',
    'startedAt',
    'status',
    'updatedAt',
    'userId',
    'variantAId',
    'variantBId',
    'winnerId',
  ] as const
  $columns = BattleSchema.$columns
  @column()
  declare battleNumber: number
  @column.dateTime()
  declare closedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare funnelStageId: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare startedAt: DateTime
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
  @column()
  declare variantAId: string
  @column()
  declare variantBId: string
  @column()
  declare winnerId: string | null
}

export class FunnelStageSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'deletedAt',
    'id',
    'name',
    'position',
    'updatedAt',
    'userId',
  ] as const
  $columns = FunnelStageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare position: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class InteractionSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'funnelStageId',
    'id',
    'interactionDate',
    'notes',
    'positioningId',
    'prospectId',
    'updatedAt',
    'userId',
  ] as const
  $columns = InteractionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare funnelStageId: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare interactionDate: DateTime
  @column()
  declare notes: string | null
  @column()
  declare positioningId: string | null
  @column()
  declare prospectId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class PositioningSchema extends BaseModel {
  static $columns = [
    'content',
    'createdAt',
    'deletedAt',
    'description',
    'funnelStageId',
    'id',
    'name',
    'updatedAt',
    'userId',
  ] as const
  $columns = PositioningSchema.$columns
  @column()
  declare content: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare funnelStageId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class ProspectPositioningSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'funnelStageId',
    'id',
    'outcome',
    'positioningId',
    'prospectId',
    'userId',
  ] as const
  $columns = ProspectPositioningSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare funnelStageId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare outcome: string | null
  @column()
  declare positioningId: string
  @column()
  declare prospectId: string
  @column()
  declare userId: string
}

export class ProspectStageTransitionSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'fromStageId',
    'id',
    'prospectId',
    'toStageId',
    'transitionedAt',
    'userId',
  ] as const
  $columns = ProspectStageTransitionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fromStageId: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare prospectId: string
  @column()
  declare toStageId: string
  @column.dateTime()
  declare transitionedAt: DateTime
  @column()
  declare userId: string
}

export class ProspectSchema extends BaseModel {
  static $columns = [
    'company',
    'createdAt',
    'deletedAt',
    'email',
    'funnelStageId',
    'id',
    'linkedinUrl',
    'name',
    'notes',
    'phone',
    'title',
    'updatedAt',
    'userId',
  ] as const
  $columns = ProspectSchema.$columns
  @column()
  declare company: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string | null
  @column()
  declare funnelStageId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare linkedinUrl: string | null
  @column()
  declare name: string
  @column()
  declare notes: string | null
  @column()
  declare phone: string | null
  @column()
  declare title: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'email', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
